// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WeatherForecast.Data;

namespace WeatherForecast.Migrations
{
    [DbContext(typeof(WeatherForecastItemDbContext))]
    [Migration("20181129013402_InitialMigrations")]
    partial class InitialMigrations
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024");

            modelBuilder.Entity("WeatherForecast.Models.WeatherForecastItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Date");

                    b.Property<string>("Summary");

                    b.Property<int>("TemperatureInCelsius");

                    b.Property<int>("TemperatureInFahrenheit");

                    b.HasKey("Id");

                    b.ToTable("WeatherForecastItem");

                    b.HasData(
                        new { Id = 1, Date = new DateTime(2018, 6, 24, 0, 0, 0, 0, DateTimeKind.Unspecified), Summary = "Scorching", TemperatureInCelsius = 32, TemperatureInFahrenheit = 89 },
                        new { Id = 2, Date = new DateTime(2018, 6, 24, 0, 0, 0, 0, DateTimeKind.Unspecified), Summary = "Mild", TemperatureInCelsius = 45, TemperatureInFahrenheit = 112 },
                        new { Id = 3, Date = new DateTime(2018, 6, 24, 0, 0, 0, 0, DateTimeKind.Unspecified), Summary = "Mild", TemperatureInCelsius = -4, TemperatureInFahrenheit = 25 },
                        new { Id = 4, Date = new DateTime(2018, 6, 24, 0, 0, 0, 0, DateTimeKind.Unspecified), Summary = "Balmy", TemperatureInCelsius = 16, TemperatureInFahrenheit = 60 },
                        new { Id = 5, Date = new DateTime(2018, 6, 24, 0, 0, 0, 0, DateTimeKind.Unspecified), Summary = "Hot", TemperatureInCelsius = 53, TemperatureInFahrenheit = 127 }
                    );
                });
#pragma warning restore 612, 618
        }
    }
}
